# リモート時とサブライブラリ作成時の基準となるパス。
main_lib = "/home/shoji/Music/main"

# サブライブラリとなるパス。
# ライブラリを生成する処理をしたいなら必須。
sub_lib = "/home/shoji/Music/sub"

# サブライブラリ作成時に変換処理を施す時のファイル形式を決める
# ffmpegで変換先のフォーマットを決めるためには必須。ドット付きの小文字を入れること
to_conv_ext = ".opus"

# 変換かけたくないファイル形式。ここに指定した拡張と一致したファイルは変換せずにコピーする。Lossyな音源を再度変換したくない時等に利用。
# ドット付きの小文字を入れること
not_conv_ext = [".mp3",".aac",".ogg",".opus",".m4a"]

# ffmpegで変換する時のオプション。配列で引数を区切る
ffmpeg_op = ["-ab","96k","-acodec","libopus"]
