# リモート時とモバイル版作成時の基準となるパス。
lib_path = "/home/shoji/Music/test"

# モバイル版のライブラリとなるパス。モバイル版のライブラリを生成する処理をしたいなら必須。
mobile_path = "/home/shoji/Music/test2"

# ffmpegで変換先のフォーマットを決めるためには必須。ドット付きの小文字を入れること
to_conv_ext = ".opus"

# 変換かけたくないファイル形式。ここに指定した拡張と一致したファイルは変換せずにコピーする。ロッシーな音源を再度変換したくない時等に利用。
# ドット付きの小文字を入れること
not_conv_ext = [".mp3",".aac",".ogg",".opus",".m4a"]

# ffmpegで変換する時のオプション。配列で引数を区切る
ffmpeg_op = ["-ab","96k","-acodec","libopus"]
